const puppeteer = require("puppeteer");
const productsLink = [
  `https://zima.com.ua/shop/krasota-i-zdorove/bandazhi/umnyj-korrektor-osanki-elektronnyj-korrektor-osanki/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/sadovoj-inventar/shlang-dlya-polivu-x-hose-37-5-m-shlang-polivochnyj-raspylitel/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/sadovoj-inventar/shlang-dlya-polivu-x-hose-52-5-m-shlang-polivochnyj-raspylitel/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/sadovoj-inventar/shlang-dlya-poliva-x-hose-60-m-s-raspylitelem-sadovyj-shlang-polivochnyj-shlang-dlya-sada/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/sadovoj-inventar/shlang-dlya-poliva-x-hose-30-m-s-raspylitelem-sadovyj-shlang-polivochnyj-shlang-dlya-sada-sinij/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/sadovoj-inventar/shlang-dlya-poliva-x-hose-15-m-s-raspylitelem-sadovyj-shlang-polivochnyj-shlang-dlya-sada/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/sadovoj-inventar/shlang-dlya-poliva-75-m-magic-hose-shlang-polivochnyj-raspylitel/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/kapuchinatory/kapuchinator-vspenivatel-mini-mikser-dlya-moloka-kofe-yaic/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/massazhery-krasota-i-zdorove/massazher-lenta-rolikovyj-massage-rope-wn-18/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/uxod-za-telom/infrakrasnyj-ruchnoj-massazher-delfin-bolshoj-40-sm-massazher-dlya-vsego-tela-dolphin/`,
  `https://zima.com.ua/shop/avtotovary-elektroinstrument-ruchnoj-instrument/massazhery/massazhnaya-podushka-massage-pillow-qy-8028-infrakrasnyj-rolikovij-massazher-dlya-shei-i-spiny-8-massazhnyx-rolika/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/slajsery/ovoshherezka-najser-dajser-nicer-dicer-plus-izmelchitel-analog-s-knigoj-receptov/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/slajsery/terka-ovoshherezka-multislajser-dlya-ovoshhej-i-fruktov-kitchen-master/`,
  `https://zima.com.ua/shop/elektronika/elektrobritvy/trimmer-massazher-4-v-1-dsp-80012-na-akkumulyatore-elektricheskij-epilyator-pilka-massazher-3w/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/apparaty-dlya-popkorna/kontaktnyj-gril-rainberg-rb-5401-nastolnyj-2200-vt/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/sadovoj-inventar/professionalnyj-privivochnyj-sekator-grafting-tool-s-3-nozhami-dlya-obrezki-i-privivki-derevev/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/elektromyasorubki/myasorubka-elektricheskaya-domotec-2017ms-elektromyasorubka-s-reversom-i-nasadkoj-dlya-kolbasy-2500vt/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/blendery/ruchnoj-blender-5-v-1-hb-2076a6-1000-vt/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/multivarki/multivarka-rainberg-rb-6207-s-frityurnicej-12-programm/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/mirksery/mikser-kuxonnyj-domashnij-dsp-km-2020a-new-design-250-vt-ruchnoj-cvet-oranzhevyj/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/mirksery/mikser-ruchnoj-rainberg-rb-1001-7-skorostej-nasadki-dlya-testa/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/blendery/blender-stacionarnyj-zepline-zp-004-blender-s-izmelchitelem-850w/`,
  `https://zima.com.ua/shop/elektronika/mashinki-dlya-strizhki/trimer-dlya-borody-rozia-hq-300-trimer-dlya-okantovki-mashinka-dlya-strizhki-trimer-dlya-usov/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/epilyatory/mashinka-trimmer-dlya-strizhki-volos-kemei-km-600-11-v-1-podstavka/`,
  `https://zima.com.ua/shop/elektronika/mashinki-dlya-strizhki/mashinka-dlya-strizhki-nabor-dlya-strizhki-mivis-vgr-v-925-chernyj/`,
  `https://zima.com.ua/shop/elektronika/mashinki-dlya-strizhki/mashinka-dlya-strizhki-volos-vgr-akkumulyatornaya-v040/`,
  `https://zima.com.ua/shop/elektronika/mashinki-dlya-strizhki/mnogofunkcionalnyj-trimmer-nabor-dlya-strizhki-volos-i-dlya-britya-i-nosa-vgr-v-012-6-v-1-chyornyj-v012/`,
  `https://zima.com.ua/shop/elektronika/mashinki-dlya-strizhki/akkumulyatornaya-mashinka-trimmer-dlya-strizhki-volos-borody-usov-vgr-v-085/`,
  `https://zima.com.ua/shop/elektronika/mashinki-dlya-strizhki/professionalnaya-mashinka-dlya-strizhki-gemei-gm-592-10-v-1/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/apparaty-dlya-popkorna/multimejker-crownberg-cb-1077-4-v-1-gril-sendvichnica-vafelnica-oreshnica/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/massazhery-krasota-i-zdorove/massazhyor-dlya-myshc-fascial-gun-hf-280-w-08-vibromassazher-dlya-myshc/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/aksessuary-krasota-i-zdorove/skladnoe-zerkalo-dlya-makiyazha-s-led-podsvetkoj-my-fold-away-mirror/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/apparaty-dlya-popkorna/sendvichnica-gril-buterbrodnica-vafelnica-crownberg-cb-1069/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/apparaty-dlya-popkorna/elektricheskaya-sendvichnica-domotec-7777ms-big-buterbrodnica-s-antiprigarnym-pokrytiem-i-termostatom-750vt/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/turizm-i-kemping/gamak-s-plankoj-80-sm-200-sm-krasnyj/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/otparivateli/vertikalnij-ruchnoj-parogenerator-otparivatel-dlya-odezhdy-rainberg-rb-6316/`,
  `https://zima.com.ua/shop/elektronika/pylesosy/pylesos-bez-meshka-grant-gt-1605-kontejnernyj-pylesos-3000-vt-universalnaya-shhetka/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/ustrojstva-dlya-volos/professionalnaya-plojka-vyravnivatel-dlya-volos-gemei-gm-416/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/odezhda-sport-zdorove-turizm/korrektor-osanki-back-pain-need-help/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/otparivateli/ruchnoj-otparivatel-dlya-odezhdy-rainberg-rb-6313-1-1500w-utyug-parovoj-vertikalnyj-otparivatel/`,
  `https://zima.com.ua/shop/elektronika/pylesosy/moshhnyj-kontejnernyj-pylesos-crownberg-cb0113-2600vt-pylesos-ciklonnyj-s-regulirovkoj-moshhnosti-luchshaya-cena/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/trenazher/trenazher-revoflex-xtreme-dlya-vsego-tela-40-uprazhnenij-rolikovyj-trenazher/`,
  `https://zima.com.ua/shop/tovary-dlya-zhivotnyx/mashinki/mashinka-dlya-strizhki-zhivotnyx-gemei-gm-6063-akkumulyatornaya-instrumenty-dlya-gruminga/`,
  `https://zima.com.ua/shop/avtotovary-elektroinstrument-ruchnoj-instrument/kamery-zadnego-vida/kamera-zadnego-vida-v-ramke-nomernogo-znaka-hd-ccd-night-vision-r314/`,
  `https://zima.com.ua/shop/uncategorized/pribor-dlya-nagreva-plavleniya-voska-dlya-depilyacij-dsp-f-70004-beauty-skincare-depilyaciya-rozovyj/`,
  `https://zima.com.ua/shop/elektronika/mashinki-dlya-strizhki/elektrobritva-muzhskaya-s-plavayushhimi-golovkamitrimmer-vgr-309v-45-akkumulyatornaya-rotornaya-chernyj/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/ustrojstva-dlya-volos/keramicheskaya-plojka-dlya-volos-geemy-gm-2815-konusnaya-plojka-dlya-lokonov/#`,
  `https://zima.com.ua/shop/krasota-i-zdorove/ustrojstva-dlya-volos/stajler-vgr-v-556-shhipcy-dlya-vypryamleniya-ukladki-i-zavivki-volos/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/trenazher/platforma-dlya-otzhimanij-push-up-rack-board-doska-dlya-otzhimanij-push-up-board/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/dlya-vannoj-komnaty/yarkij-avtomaticheskij-detskij-dozator-zubnoj-pasty-minon-luchshaya-cena/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/dlya-vannoj-komnaty/ekonomitel-vody-water-saver-new-360-gradusov-nasadka-na-kran-aerator-vodosberegayushhaya-nasadka/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/fitnes-sport-zdorove-turizm/gimnasticheskoe-sportivnoe-fitnes-koleso-double-wheel-abs-health-abdomen-round-trenazher-rolik-dlya-myshc/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/inventar-dlya-poxudeniya/plastyr-dlya-poxudeniya-mymi-wonder-patch-koreya-5-shtuk-v-nabore/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/dlya-vannoj-komnaty/dispenser-dlya-zubnoj-pasty-i-shhetok-zsw-yo1-toothbrush-sterilizer-wn-06/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/trenazher/trenazher-dlya-pressa-kreplenie-dlya-nog-na-prisoske-tm-125/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/kuxonnye-vesy/kuxonnye-elektronnye-vesy-s-chashej-rainberg-rb-02-7kg/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/trenazher/trenazher-mostik-dlya-spiny-i-pozvonochnika-back-magic-support-luchshaya-cena/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/melkaya-bytovaya-texnika/mashinka-dlya-udaleniya-katyshkov-general-electric-lint-remover-yx-5880-luchshaya-cena/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/ustrojstva-dlya-volos/plojka-pyat-voln-dlya-zavivki-volos-shhipcy-gemei-gm-2933-shhipcy-dlya-zavivki-volos-akciya/`,
  `https://zima.com.ua/shop/detskij-mir-detskie-tovary/razvitie-i-tvorchestvo/nabor-dlya-tvorchestva-medvezhonok-vodyanye-markery-art-set-20-predmetov/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/ustrojstva-dlya-volos/mini-gofre-utyuzhok-dlya-volos-dorozhnyj-dlya-prikornevogo-obema-progemei-gm2986/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/ustrojstva-dlya-volos/fen-shhetka-rascheska-3-v-1-stajler-dlya-ukladki-volos-one-step/`,
  `https://zima.com.ua/shop/elektronika/elektrobritvy/trimmer-3-v-1-dlya-strizhki-viskov-shei-borody-nosa-ushej-gm-3107/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/epilyatory/epilyator-gemei-gm-7006-4-v-1-s-akkumulyatorom-britva-s-dvojnym-lezviem-2-nasadki-epilyatora-nasadka-pemza/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/ustrojstva-dlya-volos/fen-shhetka-stajler-c-nasadkami-gemei-gm-4828-s-vrashhayushhejsya-nasadkoj/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/ustrojstva-dlya-volos/vypryamitel-dlya-volos-utyug-vgr-v-509/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/bandazhi/korset-dlya-spiny-pozvonochnika-korrektor-osanki-wo-9/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/fitnes-sport-zdorove-turizm/rezinki-dlya-fitnesu-fitness-loop-bands-komplekt-5-sht/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/ustrojstva-dlya-volos/shhipcy-gofre-gemei-gm-2955-dlya-prikornevogo-obema/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/remont/komplekt-valikov-paint-roller-dlya-pokraski-s-rezervuarom/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/fitnes-sport-zdorove-turizm/nabor-fitnes-rezinok-tkanevyx-hip-resistance/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/apparaty-dlya-popkorna/blinnica-elektricheskaya-pogruzhnaya-sinbo-sp-5208-p/`,
  `https://zima.com.ua/shop/avtotovary-elektroinstrument-ruchnoj-instrument/fm-modulyatory/fm-modulyator-fm-transmitter-car-x8-s-bluetooth-mp3-x8/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/kofevarki/kofevarka-domotec-ms0705-krasnaya/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/kofevarki/kofevarka-domotec-ms0708-chernaya/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/kofevarki/kofevarka-domotec-ms0706-belaya/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/kofemolki/elektricheskaya-rotornaya-kofemolka-rainberg-rb2207/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/rotornaya-elektricheskaya-kofemolka-600w-izmelchitel-melnica-dlya-kofe-rainberg-rb-2206/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/kofemolki/kofemolka-bytovaya-izmelchitel-rainberg-rb-2205-moshhnaya-600-w/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/kofemolki/kofemolka-elektricheskaya-raf-r-7113-seraya-kofemolka-300-vt-nerzhavejka-dlya-kofe-i-specij/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/kofemolki/kofemolka-elektricheskaya-domashnyaya-rainberg-rb-2204-400-vt/`,
  `https://zima.com.ua/shop/fonari-prozhektory-svetilniki/nochniki/nochnik-proektor-zvezdnoe-nebo-star-master-dream-qdp01-fioletovyj/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/turizm-i-kemping/skladnaya-turisticheskaya-lopata/`,
  `https://zima.com.ua/shop/elektronika/mashinki-dlya-strizhki/elektrobritva-dlya-vlazhnogo-britya-trimmer-gemei-gm-7719/`,
  `https://zima.com.ua/shop/elektronika/mashinki-dlya-strizhki/elektrobritva-dlya-vlazhnogo-britya-trimmer-gemei-gm-7719/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/elektromyasorubki/elektricheskaya-myasorubka-s-nasadkoj-dlya-tomatov-zepline-zp-002-3000-w/`,
  `https://zima.com.ua/shop/avtotovary-elektroinstrument-ruchnoj-instrument/elementy-tyuninga/vrashhayushhayasya-shhetka-nasadka-dlya-shlanga-water-blast-cleaner-roto-brush/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/apparaty-dlya-popkorna/elektro-shashlychnica-na-6-shampurov-rainberg-rb-8612-3200vt-shashlychnica-elektricheskaya-bbq/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/ustrojstva-dlya-volos/trojnaya-plojka-dlya-zavivki-volos-gemei-gm-1956/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/otparivateli/otparivatel-vertikalnyj-domotec-ms-5353-2000w/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/epilyatory/professionalnaya-besprovodnaya-mashinka-dlya-strizhki-volos-vgr-v-082-mashinka-dlya-volos-borody/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/sportivnye-aksessuary/bandazh-kolennogo-sustava-knee-support-wn-26/#`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/otparivateli/otparivatel-dlya-odezhdy-ruchnoj-dlya-doma-vertikalnyj-mnogofunkcionalnyj-200ml-1600vt-raf-darkgreen-r-1277/`,
  `https://zima.com.ua/shop/avtotovary-elektroinstrument-ruchnoj-instrument/avtomobilnye-pylesosy/avtomobilnyj-moshhnyj-pylesos-dlya-suxoj-i-vlazhnoj-uborki-the-blac-series-3-nasadki/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/organajzery-krasota-i-zdorove/organajzer-boks-dlya-kosmetiki-cosmetic-storage-box-akrilovyj/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/fitnes-sport-zdorove-turizm/gimnasticheskoe-sportivnoe-fitnes-koleso-double-wheel-abs-health-abdomen-round-trenazher-rolik-dlya-myshc/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/ustrojstva-dlya-volos/gofre-dlya-prikornevogo-obema-gemei-gm-1953-plojka-s-turmalinovym-pokrytiem/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/mebel-tovary-dlya-doma-i-sada/mnogoyarusnaya-sushilka-dlya-belya-veshhej-odezhdy-garment-rack-with-wheels-skladnaya/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/melkaya-bytovaya-texnika/kompaktnaya-mashinka-dlya-bystrogo-udaleniya-katyshek-s-odezhdy-i-mebeli-gm-216-luchshaya-cena/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/mebel-tovary-dlya-doma-i-sada/universalnaya-prochnaya-dvojnaya-napolnaya-peredvizhnaya-stojka-dlya-odezhdy-double-pole-luchshaya-cena/`,
  `https://zima.com.ua/shop/tovary-dlya-zhivotnyx/shhetki/perchatka-dlya-vychesyvaniya-shersti-true-touch-tru-tach-pet-glove/`,
  `https://zima.com.ua/shop/tovary-dlya-zhivotnyx/shhetki/perchatka-massazhnaya-shhetka-dlya-udaleniya-shersti-koshek-i-sobak-s-zashhitoj-ot-carapin-xl-147/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/remont/nabor-instrumentov-zhongxin-tools-force-108-predmetov/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/apparaty-dlya-popkorna/apparat-dlya-prigotovleniya-sladkoj-saxarnoj-vaty-v-domashnix-usloviyax-candy-maker/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/sportivnye-aksessuary/bandazh-na-stopu-elastichnyj-bint-na-pyatku-hsm-50224/`,
  `https://zima.com.ua/shop/avtotovary-elektroinstrument-ruchnoj-instrument/kamery-zadnego-vida/kamera-zadnego-vida-dlya-avtomobilya-smarttech-a101-led-luchshaya-cena/`,
  `https://zima.com.ua/shop/avtotovary-elektroinstrument-ruchnoj-instrument/avtomonitory/avtomonitor-lcd-4-3-dlya-dvux-kamer-043-monitor-avtomobilnyj-dlya-kamery-zadnego-vida-displej/`,
  `https://zima.com.ua/shop/detskij-mir-detskie-tovary/bassejny/naduvnoj-razvivayushhij-igrovoj-vodnyj-plotik-flamingo-intex-bolshoj-plot-dlya-plavaniya-dlya-kataniya/`,
  `https://zima.com.ua/shop/detskij-mir-detskie-tovary/bassejny/detskij-naduvnoj-igrovoj-centr-intex-alligator-201x170x84sm-s-gorkoj-i-aksessuarami-57165/`,
  `https://zima.com.ua/shop/detskij-mir-detskie-tovary/igrovye-nabory/naduvnye-vorota-dlya-futbola-intex-58507-140-x-89-x-81-sm-s-myachom/`,
  `https://zima.com.ua/shop/detskij-mir-detskie-tovary/bassejny/intex-naduvnoj-edinorog-57561-np-4-razmerom-201x140x97sm/`,
  `https://zima.com.ua/shop/detskij-mir-detskie-tovary/bassejny/semejnyj-bassejn-intex-28101-easy-set-183x150x51-sm/`,
  `https://zima.com.ua/shop/detskij-mir-detskie-tovary/igrushki-dlya-plyazha/naduvnoj-plotik-edinorog-intex-163x86-57552/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/bytovaya-texnika/otparivatel-ruchnoj-parogenerator-paroochistitel-vertikalnyj-dsp-kd-1079/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/uvlazhniteli-vozduxa-tovary-dlya-doma-i-sada/uvlazhnitel-vozduxa-saturn-s-led-podsvetkoj-3-rezhima-ot-usb-el-544-31-200-ml/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/mirksery/elektricheskaya-sokovyzhimalka-crownberg-cb-3402/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/sokovyzhimalki/sokovyzhimalka-crownberg-cb-3401/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/kondicionery/ventilyator-moshhnyj-napolnyj-domotec-ms-1620-s-tajmerom-otklyucheniya/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/otparivateli/ruchnoj-otparivatel-dlya-odezhdy-zepline-zp-037/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/kofemolki/rotornaya-kofemolka-izmelchitel-elektricheskaya-rainberg-rb-302-na-50-gramm-300-vatt-chernaya/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/sadovoj-inventar/sadovye-perchatki-s-kogtyami-garden-genie-glovers/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/mebel-tovary-dlya-doma-i-sada/polki-dlya-obuvi-shoe-rack-4-polki-16-par/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/organajzery-tovary-dlya-doma-i-sada/nastolnyj-yashhik-organajzer-dlya-xraneniya-kosmetiki-s-zerkalom-trm-7009-belyj/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/mebel-tovary-dlya-doma-i-sada/stojka-dlya-xraneniya-obuvi-utm-shoe-rack-5-polok/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/mebel-tovary-dlya-doma-i-sada/stol-alyuminievyj-raskladnoj-dlya-piknika-4-stula-chemodan/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/naduvnye-matrasy/ortopedicheskaya-podushka-pod-spinu-back-support-pillow-comfy-curve/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/dlya-vannoj-komnaty/polka-tualetnaya-organajzer-nad-unitazom-storey-toilet-rack-580x75x300-mm-dlya-xraneniya-veshhej/`,
  `https://zima.com.ua/shop/elektronika/vesy/vesy-napolnye-steklyannye-rainberg-rb-2003a-kruglye-na-180-kg-s-termometrom/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/mebel-tovary-dlya-doma-i-sada/naduvnoe-sadovoe-kreslo-s-pufikom-air-sofa-comfort-zd-33223-velyur-76130-sm/`,
  `https://zima.com.ua/shop/detskij-mir-detskie-tovary/prinadlezhnosti-po-uxodu/palatka-detskaya-s-bassejnom-avtomaticheskaya-wm-baby-pool/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/mebel-tovary-dlya-doma-i-sada/skladnoj-karkasnyj-tkanevyj-shkaf-storage-wardrobe-88130-shkaf-na-tri-sekcii-13045175/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/naduvnye-matrasy/spalnyj-meshok-odeyalo-champion-s-kapyushonom-kamuflyazhnyj/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/turizm-i-kemping/palatka-avtomaticheskaya-4-x-mestnaya-zelenaya-razmer-2x2-metra/`,
  `https://zima.com.ua/shop/avtotovary-elektroinstrument-ruchnoj-instrument/avtomagnitoly/2din-magnitola-pioneer-7018-usbsdbluetoothpult-na-rul-korotkaya-baza/                                                                                                                                                                               `,
  `https://zima.com.ua/shop/avtotovary-elektroinstrument-ruchnoj-instrument/avtomagnitoly/moshhnaya-avtomagnitola-s-chistym-zvukom-jsd-520bt-s-usb-i-bluetooth-luchshaya-cena/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/turizm-i-kemping/palatka-avtomaticheskaya-6-ti-mestnaya-zelenaya-razmer-2x25-metra/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/uvlazhniteli-vozduxa-tovary-dlya-doma-i-sada/ultrazvukovoj-aromadiffuzor-s-imitacionnym-effektom-ognennogo-plameni/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/apparaty-dlya-popkorna/aero-frityurnica-cifrovaya-bezmaslyannaya-frityurnica-6-litrov-silver-crest-s-18-2400w/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/apparaty-dlya-popkorna/shashlychnica-elektricheskaya-kuxonnaya-crownberg-cb-7415-shashlyk-doma-5-shampurov-1000-vt-nerzhavejka-k/`,
  `https://zima.com.ua/shop/detskij-mir-detskie-tovary/razvitie-i-tvorchestvo/cifrovoj-detskij-fotoapparat-teddy-gm-24-rozovyj-mishka-smart-kids-camera-rozovyj/                                                                                                                                                                                `,
  `https://zima.com.ua/shop/sport-zdorove-turizm/turizm-i-kemping/turisticheskij-gamak-s-moskitnoj-setkoj-ukc-hammock-net-zelenyj-do-200-kg/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/gamak-dvojnoj-s-moskitnoj-setkoj-hammock-with-net-army-dlya-otdyxa-do-200-kg/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/slajsery/ovoshherezka-izmelchitel-veggie-slicer-14-v-1-sitechko-dlya-yaic-i-nozh-dlya-ochistki-ovoshhej-ka-808/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/izmelchiteli/ovoshherezka-multislajser-safe-slice-mandoline-coolice/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/blendery/moshhnyj-kompaktnyj-bystryj-blender-s-dvuxyarusnym-lezviem-molniya-luchshaya-cena-2/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/blendery/blender-pogruzhnoj-4-v-1-jamaky-3004a-1000w-s-venchikom-chashej-izmelchitelem-i-mernym-stakanom-gs-6273/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/ustrojstva-dlya-volos/trojnaya-plojka-dlya-zavivki-volos-kemei-jfq-km-2022/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/uvlazhniteli-vozduxa-tovary-dlya-doma-i-sada/uvlazhnitel-vozduxa-humidifier-h20-cat-art8023/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/turizm-i-kemping/palatka-avtomaticheskaya-tryoxmestnaya-dt-2-x-15-m-best-1/`,
  `https://zima.com.ua/shop/sport-zdorove-turizm/turizm-i-kemping/prochnaya-vmestitelnaya-palatka-avtomaticheskaya-dt-2-x-2-m-best-2/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/mebel-tovary-dlya-doma-i-sada/peredvizhnaya-napolnaya-veshalka-dlya-odezhdy-the-new-coat-rack-chernyj/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/mebel-tovary-dlya-doma-i-sada/prostaya-skladnaya-polka-dlya-obuvi-4-polki-shtabeliruemaya-plastikovaya-polka-dlya-obuvi/`,
  `https://zima.com.ua/shop/detskij-mir-detskie-tovary/razvitie-i-tvorchestvo/nabor-dlya-tvorchestva-v-alyuminievom-chemodane-002-84-predmeta-nabor-dlya-risovaniya-v-kejse/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/kuxonnye-prinadlezhnosti/professionalnyj-nabor-nozhej-zepline-zp-046-nabor-kuxonnyx-nozhej-7-predmetov-seryj/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/apparaty-dlya-popkorna/parovarka-s-fiksirovannymi-ruchkami-skorovarka-6-l/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/kofevarka-dlya-doma-elektricheskaya-turka-na-4-chashki-250ml-400vt-dsp-ka-3047/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/kuxonnye-prinadlezhnosti/nabor-razemnyx-form-dlya-vypechki-vypekaniya-korzhej-tortov-keksov-serdce-krug-kvadratunique-un-1703-3-v-1/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/kondicionery/ventilyator-napolnyj-king-rex-crown-fs-1602-40w/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/kondicionery/napolnyj-ventilyator-rainberg-rb-1601/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/kuxonnye-nabory/nabor-razemnyx-iz-3-form-dlya-vypechki-unique-un-1702/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/multivarki/multivarka-zep-line-zp-060/`,
  `https://zima.com.ua/shop/detskij-mir-detskie-tovary/kopilki/sejf-robot-kopilka-detskaya-robot-bodyguard-s-otpechatkom-palca-muzykalnaya-goluboj/`,
  `https://zima.com.ua/shop/detskij-mir-detskie-tovary/kopilki/sejf-robot-kopilka-elektronnaya-detskaya-robot-bodyguard-s-otpechatkom-palca-muzykalnaya-rozovyj/`,
  `https://zima.com.ua/shop/detskij-mir-detskie-tovary/razvitie-i-tvorchestvo/nabor-sketch-markerov-48-sht-dlya-risovaniya-dvustoronnix-touch/`,
  `https://zima.com.ua/shop/detskij-mir-detskie-tovary/razvitie-i-tvorchestvo/nabor-sketch-markerov-60-sht-dlya-risovaniya-dvustoronnix-touch/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/dlya-uborki/shvabra-dlya-pola-x-type-s-otzhimom-37-sm-i-tremya-nasadkami/`,
  `https://zima.com.ua/shop/kolonki-i-akusticheskie-sistemy/portativnye/kolonka-s-led-podsvetkoj-muzykalnaya-portativnaya-bluetooth-am-303/`,
  `https://zima.com.ua/shop/kolonki-i-akusticheskie-sistemy/portativnye/portativnaya-kolonka-bluetooth-arivans-hopestar-h46/`,
  `https://zima.com.ua/shop/kolonki-i-akusticheskie-sistemy/portativnye/kolonka-hoco-bs30-new-moon-besprovodnoj-dinamik-v5-0-s-litievoj-batareej-2000mah-klassa-a-6-chasov-raboty-2/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/dlya-uborki/shvabra-s-funkciej-otzhima-vrashhayushhayasya-na-360-reguliruemaya-shvabra-teleskopicheskaya-shvabra-dlya-uborki/`,
  `https://zima.com.ua/shop/vse-dlya-kuxni/slajsery/ovoshherezka-s-kontejnerom-nicer-dicer-quick-2-5-v-1/`,
  `https://zima.com.ua/shop/krasota-i-zdorove/ustrojstva-dlya-lica/mini-elektricheskaya-ochishhayushhaya-shhetka-dlya-lica-sonic-vibration-cleanser/`,
  `https://zima.com.ua/shop/tovary-dlya-doma-i-sada/kondicionery/ventilyator-wimpex-wx707-180-mm-50-bt-nastolnyj-na-prishhepke/`,
];

(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();

  for (let i = 0; i < productsLink.length; i++) {
    let link = productsLink[i];
    await page.goto(`${link}`);
    let arr = await page.evaluate(() => {
      let text = document.querySelector(".all-more-many").innerText;
      return text;
    });

    console.log(arr);
  }

  await browser.close();
})();

// артикул - .sku
// наличие - .all-more-many
// название - .product_title
